# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: CIMI-Vital-Signs
canonical: http://hl7.org/fhir/us/vitals
version: 0.2.0
name: cimi-vital-signs
title: Vital Signs with Qualifying Elements
status: draft
publisher:
  -
    name: HL7 International - Clinical Information Modeling Initiative
    url: http://hl7.org/Special/committees/cimi
  -
    name: Logica
    url: https://www.logicahealth.org/
description: This IG describes vital signs observations that include qualifying information such as cuff size for blood pressure, or an associated situation of "during exercise" for blood pressure or heart rate, etc.
fhirVersion: 4.0.1
dependencies: 
  hl7.fhir.us.core: 3.1.1
copyrightYear: 2021+
copyright: Logica Health, all rights reserved Creative Commons License
releaseLabel: STU 1
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
packageId: hl7.fhir.us.vitals
parameters:
  show-inherited-invariants: false
  path-expansion-params: ../../exp-params.json

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

pages:
  index.md:
    title: Home
  profiles.md:
    title: Profiles
  terminology.md:
    title: Terminology
  all-examples.md:
    title: Examples
  downloads.md:
    title: Downloads
menu:
  IG Home: index.html
  Profiles & Extension: profiles.html
  Examples: all-examples.html
  Terminology: terminology.html
  Downloads: downloads.html
  Artifacts: artifacts.html